language: node_js
node_js:
  - '0.11'
  - '0.10'
addons:
  code_climate:
    repo_token: 6d530fb2d5bea28e94ea45921523a35c6c9f2f45c55bed0b0dfe38571a5d01af
after_script:
  - cat ./coverage/lcov.info | codeclimate
  - npm run clean
